# Generated by Django 6.1 on 2026-08-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('TRANSPORTE', 'Transporte'), ('MORADIA', 'Moradia'), ('LAZER', 'Lazer'), ('SAUDE', 'Saúde'), ('EDUCACAO', 'Educação'), ('SALARIO', 'Salário'), ('OUTROS', 'Outros')], max_length=20)),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('PIX', 'Pix'), ('TRANSFERENCIA', 'Transferência')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_lancamento', models.DateField()),
                ('recorrente', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data_lancamento'],
            },
        ),
    ]
